use terraform in plan action since terragrunt would swallow the error

diff --git a/.github/workflows/terraform-plan.yaml b/.github/workflows/terraform-plan.yaml
--- a/.github/workflows/terraform-plan.yaml
+++ b/.github/workflows/terraform-plan.yaml
@@ -28,11 +28,6 @@ jobs:
       - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
         with:
           terraform_wrapper: false
-      - name: Setup Terragrunt
-        uses: autero1/action-terragrunt@22b4647f1263865cda4473831640e71d349db2cd # 1.3.2
-        with:
-          terragrunt_version: 0.51.0
-          token: ${{ secrets.GITHUB_TOKEN }}
       - name: plan
         env:
           ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
@@ -43,10 +38,9 @@ jobs:
           set -e
           export ARM_OIDC_REQUEST_TOKEN=$ACTIONS_ID_TOKEN_REQUEST_TOKEN
           export ARM_OIDC_REQUEST_URL=$ACTIONS_ID_TOKEN_REQUEST_URL
-          sh scripts/terragrunt-init.sh
-          terragrunt plan -no-color -out tfplan | tee tfplan.txt
-          terraform show -json tfplan | jq empty
-          echo $?
+          terraform init || echo "Terraform init error but we tolerate it here."
+          terraform init -reconfigure
+          terraform plan -no-color -out tfplan | tee tfplan.txt
       - name: Azure login
         uses: azure/login@a65d910e8af852a8061c627c456678983e180302 #v2.2.0
         with:
